### ISSUE TITLE
[Teamkerbell] 기능 구현가능한지 궁금합니다

### ISSUE THREAD

**Issue by seongahjo** [D2CAMPUS-FEST/2015#10]
Client들의 화면을 캡쳐 할 수 있는 기능을 구현하고자 합니다.
불가능하다고 생각하지만 혹시라도 위와 같은 기능을 구현할 수 있는 관련 라이브러리가 존재하는지 
궁금하여 질문을 올립니다.

**Comment by MyeongKim** [comment]
단순 화면 캡쳐를 의미하시는 거라면, 저는 지난 프로젝트에서 https://html2canvas.hertzen.com/ 를 사용했습니다.

**Comment by MyeongKim** [comment]
구글에서 키워드 'javascript screen capture library' 로 검색했습니다.

**Comment by kbu1564** [comment]
@mingkim 처음 답변다신 내용의 링크가 깨졌네요 :)

**Comment by minarc** [comment]
@kbu1564 '를'까지 링크 걸려서 그래요. '를'지우고 접속 해 봐요

**Comment by MyeongKim** [comment]
답변 수정했습니다. 감사합니다~

**Comment by egaoneko** [comment]
저희도 그래프를 이미지로 제공하기 위해서, @mingkim 님께서 말씀해주신 html2canvas를 사용하고 있어요. 단지 해당 라이브러리를 사용해서 Safari에서 이미지 다운로드를 제공하려면, 추가적인 작업이 필요한 것 같네요.

**Comment by disjukr** [comment]
[phantomjs](http://phantomjs.org/) 등을 사용해서 클라이언트와 같은 데이터로 서버에서 페이지를 렌더링한 다음 캡쳐를 하는 방법도 있을 것 같습니다: http://phantomjs.org/screen-capture.html
