### ISSUE TITLE
[Teamkerbell] 라이브러리 관련 질문입니다

### ISSUE THREAD

**Issue by seongahjo** [D2CAMPUS-FEST/2015#11]
직접 개발하기도 하지만 아직 실력이 부족하여 익숙치 않은 곳에서는 라이브러리를 사용하곤 하는데 
아직은 미숙한지라 라이브러리를 검색하는데 있어 많은 시간이 소요됩니다. 
다들 사용하고 계시는 라이브러리를 찾았을 때 어느 곳에서 어떤식으로 검색 하는지 궁금합니다.
혹시 라이브러리를 모아둔 사이트같은게 있는지 궁금합니다.

**Comment by minarc** [comment]
구글이요, 또 그렇게 많은 시간이 소요되고 해결되지 않는 것을 도움받기 위해서 여기 이슈 트래커에 올리시면 출중한 실력을 가지신 분들이 잘 알려 주실 것 같네요.

깃허브 자체에도 키워드를 입력 해 보시면 좋은 라이브러리가 나오곤 합니다.

**Comment by MyeongKim** [comment]
저는 라이브러리와 관련된 키워드로 구글링을 하고, 가끔씩 
- http://haruair.com/javascript-%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC-%EB%AA%A8%EC%9D%8C
- http://freebiesbug.com/code-stuff/js-effects-plugins/

이런 사이트에서도 좋은게 있으면 링크를 저장해요...!

**Comment by minarc** [comment]
봐요 저렇게 잘 도와주십니다...

**Comment by kbu1564** [comment]
저도 구글링이 대부분이고 깃허브 repository 검색하여 사용하곤 합니다.
깃허브에서 특정 언어를 타겟으로 하는 프로젝트 검색이 가능합니다.

**Comment by minarc** [comment]
프로젝트 ReadMe를 읽어보니 아직 jQuery는 사용하지 아니 하시는 것 같기도 합니다.
jQuery를 이용한 다양한 라이브러리가 많습니다.

**Comment by egaoneko** [comment]
저도 구글링하고 있어요. 주로 사용할 언어 + 사용할 기능을 키워드로 검색하고, 검색 결과를 보고 검색 키워드를 조금씩 수정하는 방식으로 찾고 있어요.
