### ISSUE TITLE
[QuesCheetah] 오픈소스에서의 모듈화

### ISSUE THREAD

**Issue by MyeongKim** [D2CAMPUS-FEST/2015#15]
프로젝트 url : https://github.com/mingkim/QuesCheetah

오픈소스 프로젝트를 진행하면서, 소스코드를 내 반복되는 부분을 모듈화하려고 합니다.
프로젝트 개발의 편의성과 정확성, 효율을 생각하면 모듈화를 시키는게 더 좋은 것 같지만,
오픈소스 프로젝트를 사용하는 사람의 입장에서는 모듈화가 오히려 코드 복잡도를 증가시키고 가독성을 낮춥니다.

작년에 갔던 컨퍼런스 세션에서도 관련된 내용이 있었습니다. [발표자료 링크](http://playnode.io/assets/download/modular-vs-monolith.pdf)
여기선 flat한 structure 가 nested structure보다 더 낫다고 주장하셨는데, 다른분들께서는 어떻게 생각하시는지 알고 싶습니다.

**Comment by minarc** [comment]
저도 MVC 패턴을 구현하면서 많이 들었던 생각입니다. 추가 확장이 썩 필요할 것 같진 않은데 괜시리 모듈화 해서 복잡히 할 바에야 좀 flat(?)하게 하더라도 편하게 갈 생각을...... 
하지만 이것이 다른 사람들이 추가 기능을 만들어 참여 할 오픈 소스 프로젝트라는 관점에서 볼 때에는 모듈화가 필요하다고 생각했습니다. 
이것이 아니라면 아예 간단하고 편할 대로의 나만의 식대로 구현하고 알기 쉽게 설명한 그림과 문서를 함께 넣을까...... 생각도 해 봤습니다. 프로젝트의 구조는 한 번 결정하고 나면 뒤에 다시 갈아 엎어 버리기엔 힘이 많이 드니까요 -,.-; 지금의 저처럼...

**Comment by egaoneko** [comment]
기존에 만들던 사람이 아니라 추가로 들어오는 경우라면, 잘 모듈화 되있는 쪽이 더 좋지 않을까요?
추가로 들어온 사람이 반복되는 부분 등 구조를 파악하려면 더 힘들 것 같아서요.

제가 경우는.. 제가 만든 코드의 정리되지 않은 반복되는 부분에서 난감할 때가 생기네요. ㅠㅠ
