### ISSUE TITLE
[SetupBox] SVN 관련 기능을 어떤 방법으로 개발하면 좋을까요?

### ISSUE THREAD

**Issue by jafffy** [D2CAMPUS-FEST/2015#19]
github url : https://github.com/maxtortime/SetupBox
issue url : https://github.com/maxtortime/SetupBox/issues/3

저희 프로젝트는 마치 Dropbox의 desktop client와 같이 특정한 폴더의 내용을 버전관리 해주고 서버와 syncing 해주는 역할의 클라이언트를 작성하려고 합니다.

저희는 이 과정에서 SVN C API를 사용하기로 결정하였는데요, 이 방향으로 가는데 저희에겐 총 세가지 안이 있습니다.
- python svn module(https://pypi.python.org/pypi/svn)
  - python으로 wrapping 된 SVN C API
  - 너무 버전이 낮아서 믿을 수 있는지 의심됨
- subversion C API
  - Apache Subversion에서 공식적으로 지원하는 C API
- C로 제작한 모듈을 python에서 importing 해서 사용하는 방법
  - 자체 wrapper를 필요한 부분만 제작하여 python으로 클라이언트를 작성하는 방법.
  - 이런 방식으로 wrapping을 해본 경험이 없어 좋은 접근일지 궁금함

저희 팀은 python을 써보긴 했지만 아주 잘 쓰는 정도는 아니고, C를 가지고는 만들어본 경험이 많은 상태라서 이번에 Python extending을 시도를 해볼지, 아니면 그냥 C base로 작성을 하는게 좋을지 고민이 되네요.

감사합니다.

**Comment by youknowone** [comment]
질문에 대한 답은 아니지만, 꼭 svn을 써야하는게 아니라 버전관리도구가 필요한거면 mercurial을 쓰시면 어떨까 싶네요. mercurial은 파이썬으로 개발된 버전관리도구여서 파이썬으로 다루기도 쉽고 svn보다 안전하게 관리하기도 쉬울거에요.
https://www.mercurial-scm.org/wiki/PythonHglib

**Comment by MyeongKim** [comment]
이미 알고 계실것 같지만 
python svn module(https://pypi.python.org/pypi/svn) 의 링크에서 Downloads 정보란에 

234 downloads in the last day
1756 downloads in the last week
5556 downloads in the last month

으로 다운로드가 꽤 되는 편이고, 마지막 커밋이 작년 중반에 된 것 같으니 괜찮지 않을까요?

**Comment by jafffy** [comment]
@youknowone:
제가 지식이 부족해서 그런데, 혹시 mercurial 도 git처럼 snapshot base로 관리를 하나요? 제가 svn을 선택한 이유는 diff base기 때문에 스토리지 시스템에 적합하다고 생각했기 때문이거든요.

@mingkim:
검토해보겠습니다. 의견 감사합니다.

**Comment by jafffy** [comment]
오늘 토의 및 구조 변경으로 위 이슈는 중요한 이슈가 아니게 되어서 이슈를 닫아도 될 것 같네요.
관심 가져주신 분들 감사드립니다.

**Comment by MyeongKim** [comment]
@jafffy 
발표하실때 diff base 로 가야 한다고 말씀하신 것 같은데 구조가 어떻게 변경되었는지 알 수 있을까요? (개인적인 궁금함에..)

**Comment by jafffy** [comment]
@mingkim 관심 가져주셔서 감사합니다:)

원래 저희는 open source로 클라우드 서비스를 만드는 모델을 선택하려고 했는데, 어제 모임 이후 팀원들끼리 토의해서 차라리 서비스가 아닌 storage cloud를 만들기 위한 엔진을 만드는 방향으로 선택을 바꿨습니다. 더 컴팩트하고 기능 중심적이고, 다른 스토리지 클라우드를 만드려는 사람이 쉽게 가져다 쓸 수 있는 형태로 제공하기 위해서요.

현재 계획된 storage cloud engine의 기능은 아래와 같습니다.
- diff module: 특정 binary file formats의 diff를 지원해 주는 모듈 (e.g. executable file, image file...)
- fs module: file I/O의 최적화 및 동기화 타이밍을 제어할 수 있는 모듈
- transaction module: 서버와 동기화를 하기 위한 transaction을 관리하는 모듈
- 그 외, service를 위한 여러 모듈들: authentication module 등
  
  목표로 해서 구현하는 것이 좋겠다는 판단이 들었습니다.

더불어 이러한 엔진을 이용한 Demo application 정도는 만들어서 여러분들이 쉽게 기여하실 수 있고 저희도 테스트를 잘 할 수 있는 환경을 만드는 정도로 서비스는 간단하게 만들기로 계획했습니다.

이에 특별히 @jcooky 님께서 많은 조언을 해주셨습니다.

이러한 내용에 대한 간단한 요약은 곧 저희 프로젝트 위키에 작성되어서 공유될 예정입니다. (아마 이번 주 일요일 안에는 올라갈 것이라고 예상하고 있구요.)

다시 한번 관심 가져주셔서 감사합니다.

**Comment by jafffy** [comment]
@mingkim :
참고로 어떤 binary format을 지원할 지에 대한 이슈가 저희 프로젝트에 걸려 있는데, 여기에 아이디어를 주시는 것이 되게 저희에겐 도움이 됩니다.

혹시 좋은 아이디어가 있으시면 써주시면 좋을 것 같네요.

아래 링크의 이슈입니다.
https://github.com/maxtortime/SetupBox/issues/13
