### ISSUE TITLE
[ward] 수집된 데이터 분석

### ISSUE THREAD

**Issue by egaoneko** [D2CAMPUS-FEST/2015#21]
수집된 데이터를 분석하는 부분에 대해 고민하고 있습니다.

수집된 데이터를 분석하여 의미있는 내용들을 뽑아서 보여주고 싶은데, 어떤 방식으로 접근해야할지 잘 모르겠습니다.

현재 제가 생각하고 있는 것은 저장되어 있는 데이터를 형태소를 분석하여, 좋아요 수와 댓글 수로 점수를 매기어 해당 그룹에서 인기있는 키워드를 찾아 보여주고, 이 데이터를 바탕으로 새로 작성되는 게시글을 보여주는 순서를 변경해 보여주는 방식인데 어떨지 모르겠네요.

**Comment by Rumo-Arf** [comment]
좋아요로 점수 매기고 이런 부분은 전에 제가 해 본 거랑 정말 흡사하네요...... 형태소 분석은 국민대 강승식 교수님의 라이브러리가 유명합니다. 근데 지금 연구실 홈페이지가 들어가지질 않네요...

[구글 검색](https://www.google.co.kr/webhp?hl=ko#newwindow=1&safe=off&hl=ko&q=%EA%B5%AD%EB%AF%BC%EB%8C%80+%ED%98%95%ED%83%9C%EC%86%8C+%EB%B6%84%EC%84%9D%EA%B8%B0)

**Comment by egaoneko** [comment]
@Rumo-Arf 페이스북에서 가지고온 데이터 중에 점수를 매길만한 의미있는 부분을 고민해봤는데 좋아요랑 댓글밖에 떠오르지 않더라고요. 공유같은 경우는 큰 의미가 없어보이더라고요. 저기에 Python 그룹이면 Python과 관련된 키워드는 점수를 더 주거나 이러고 싶은데.. 이건 해당 그룹의 관련된 키워드를 어떻게 생성해야 할지도 감이 안잡히네요.

**Comment by Rumo-Arf** [comment]
@egaoneko 결국 빅 데이터에서 어떻게 의미있는 걸 도출해서 시각화 할지가 고민이라는 걸까요? 아직 팀 내에서 이걸 의논 중일 수도 있겠네요...

해당 그룹의 관련 키워드는 아마 그룹에 Tag 같은 리스트가 있는 것으로 알아요. 거기서 뽑아내면 될 것 같습니다. 하지만 어떤 키워드와 어떤 단어에 더 많은 가중치를 줄지는 신중하게 결정해야 해요.

일단 궁극적으로 어떤 데이터를 시각화 해서 어떤 의미를 갖게 할 건지 확실하게 방향을 잡아야만 할 것 같아요. 그렇지 않으면 구체적인 목적없이 그저 뜬구름 잡는다는 질타를 받기 쉬워 보입니다.

**Comment by egaoneko** [comment]
@Rumo-Arf 역시 어렵네요. ㅠㅠ;; 저희도 이 부분에 대해서는 고민중에 있어요.

**Comment by Rumo-Arf** [comment]
@egaoneko https://www.youtube.com/watch?v=nYhUfEUaybo 이 영상이 도움이 될 거에요. '데이터 시각화'라는 주제에 대해서 조사 해 보고 팀에서 다시 한 번더 의논 해서 어떤 주제를, 누구를 대상으로, 어떤 정보를 전달 해 줄지가 관건인 것 같습니다 :^)

**Comment by egaoneko** [comment]
@Rumo-Arf 좋은 자료 감사드립니다. 팀원과 함께 보고 의논해보겠습니다~

**Comment by jafffy** [comment]
저는 Konlpy(http://konlpy.org/en/v0.4.4/)를 이용해서 비슷한 word counter 를 만들어 본 경험이 있습니다. 참고하시면 쉽게 하실 수 있을 것 같네요.

또한, 평가 식을 만드는 부분은 원래 어려운 부분으로 알고 있어서 나중에 밋업 주제로 Data science 하시는 분 모셔서 조언을 다같이 듣는 것도 좋을 것 같다는 생각이 드네요.

**Comment by egaoneko** [comment]
@jafffy 답변 감사드립니다. Konlpy도 고려해보겠습니다.
가능하다면 밋업 주제로 조언을 받으면 좋을 것 같네요.
