### ISSUE TITLE
[QuesCheetah] 소켓 서버 구현

### ISSUE THREAD

**Issue by MyeongKim** [D2CAMPUS-FEST/2015#23]
소켓 서버를 따로 만들어서 유저의 api call 에 대한 결과값을 return 하려고 합니다.
node.js + socket.io 로 소켓 서버를 만들고 현 api 서버 (python+django+MySQL)와 통신하기 위한 broker로 RabbitMQ 를 사용하려고 하는데 broker 서버로 Redis 가 더 나을지 아니면 더 좋은 다른 방법이 있는지 궁금합니다. 

Redis 를 key-value datastore 용도로 사용하지는 않을 생각이기 때문에 단순히 queue 용도로만 놓고 비교한다면
RabbitMQ 의 속도가 더 빠르다는 결과가 있습니다.
자료 : http://www.minvolai.com/blog/2013/10/RabbitMQ-vs-Redis-as-Message-Brokers/rabbitmq-vs-redis-message-broker/

**Comment by bluemir** [comment]
RabbitMQ가 Message Queue로서는 Redis보다 낫지요. RabbitMQ는 아에 전문적(?)으로 MQ를 노리고 만들었고 Redis는 목적자체가 In memory storage 라고 알고 있습니다. 그래서 RabbitMQ는 여러가지 [메세지 모델](https://www.rabbitmq.com/getstarted.html)을 제공하는 반면에 Redis는 그러하지 못한다고 알고 있습니다. 물론 Redis로도 MQ처럼 사용할수 있긴 하지만, 좀더 메세지 큐로서의 기능이나 편의성을 신경쓴 RabbitMQ가 낫지 않나 싶습니다.

**Comment by MyeongKim** [comment]
@bluemir 감사합니다.
