### ISSUE TITLE
★ [공지] 첫 번째 밋업 주제 제안 & 참가확인

### ISSUE THREAD

**Issue by Kang-heesuk** [D2CAMPUS-FEST/2015#24]
1월 29일(금) D2 StartupFactory에서 첫 번째 밋업이 진행됩니다.

참가자들끼리 논의해보고 싶은 주제가 있다면 이슈로 등록해주세요~
오프라인 멘토링을 원하시는 주제를 남겨주셔도 좋아요!

발표(or 공유)하고 싶은 주제가 있다면 HOST로 Lightening talk을 진행하셔도 very good!! :sparkles: 

> 시간 : 오후 2시 - 7시
> - 오후 2시 - 5시 : 자유롭게 프로젝트 개발 및 토론 (개발자 Café처럼)
> - 오후 5시 - 7시 : Lightening Talk 
>                             (참가자끼리 서로 밋업주제에 대해 생각을 나누고 토론 + NAVER 개발자도 함께)

※ 첫 번째 밋업에 참여를 원하시는 분은 댓글과 주제 남겨주세요!

**Comment by Kang-heesuk** [comment]
지금까지 등록된 주제
- #3 오픈 소스 프로젝트는 어떻게 홍보해야 할까?
- #8 소프트웨어의 목적에 맞는 디자인 패턴 외

**Comment by mingkim** [comment]
@Kang-heesuk 

내일(22일) 진행되는 멘토링 진행에 대해 궁금한 점이 있습니다.
내일은 개별 프로젝트 이슈와는 상관없이 [오픈소스 협업, 운영, 기여] 에 대한 주제로만 진행되는 건가요?

**Comment by Kang-heesuk** [comment]
@mingkim 남겨주신 이슈는 내일 참석하시는 멘토분들께 전달드렸습니다. 각 멘토분들과 질의응답 시간도 마련되어 있으니 오프라인으로도 이야기 나누셔도 좋습니다. 전달드린 협업/운영/기여는 강의 주제로 테마별 자세한 컨텐츠는 곧 전달드리도록 하겠습니다. :) 내일뵈어요~

**Comment by mingkim** [comment]
@Kang-heesuk 
감사합니다!

**Comment by Rumo-Arf** [comment]
참가 가능 합니다.

**Comment by KimBoWoon** [comment]
[SUJI] 1월 29일 밋업 수지팀 3명 전원 참가합니다.

**Comment by seungwee-choi** [comment]
[CodeFolio] 1월 29일 밋업 3명 전원 참가합니다.

**Comment by Yoseob** [comment]
[Trevi] 1월29일 밋업 3명 전원참가 합니다.

**Comment by maxtortime** [comment]
[SetupBox] 1/29 밋업 2명 참가하겠습니다.

**Comment by egaoneko** [comment]
[ward] 1/29 밋업 1명 참가하겠습니다.

**Comment by MyeongKim** [comment]
[QuesCheetah] 1/29 밋업 1명 참가합니다.

**Comment by hj0212** [comment]
[SURRO] 1/29 밋업 2명 참가합니다

**Comment by kbu1564** [comment]
[SecurityBootManager] 1/29 밋업 2명 참가합니다

**Comment by MyeongKim** [comment]
@Kang-heesuk 

Lightening talk 발표 신청해도 될까요? 아직 주제가 자세하게 정해지진 않았지만 REST API 에 대해 발표하려고 합니다.

**Comment by Kang-heesuk** [comment]
@mingkim 네네 아주아주 좋습니다 :)

**Comment by maxtortime** [comment]
아 REST API 듣기만 듣고 잘 몰랐는데 꼭 들어야겠네요.
@mingkim 기대하겠습니다! ㅎㅎ

**Comment by MyeongKim** [comment]
REST API refactoring 발표 슬라이드 입니다.

http://slides.com/mingkim/restapi#/

**Comment by jcooky** [comment]
[Jandy] 1/29 밋업 1명 참가합니다.
이제서야 발견해갔고 늦게 신청해서 죄송합니다
