### ISSUE TITLE
★ [공지] 두 번째 밋업 주제 제안 & 참가확인

### ISSUE THREAD

**Issue by Kang-heesuk** [D2CAMPUS-FEST/2015#28]
2월 4일(목) D2 StartupFactory에서 두 번째 밋업이 진행됩니다.

참가자들끼리 논의해보고 싶은 주제가 있다면 이슈로 등록해주세요~
발표(or 공유)하고 싶은 주제가 있다면 HOST로 Lightening talk을 진행해도 좋아요! :sparkles: 

> 시간 : 오후 2시 - 7시
> - 오후 2시 - 5시 : 자유롭게 프로젝트 개발 및 토론 (개발자 Café처럼)
> - 오후 5시 - 7시 : Lightening Talk 
>                         참가자끼리 서로 주제에 대해 생각을 나누고 토론 + (optional)w/ NAVER 개발자

※ 두 번째 밋업에 참여를 원하시는 분은 댓글과 주제 남겨주세요!
주제는 많은 분들이 관심갖고 이야기 나눌 수 있는 주제면 더 좋을 것 같습니다. :)

**Comment by MyeongKim** [comment]
[QuesCheetah] 2/4 밋업 1명 참가합니다.

**Comment by seungwee-choi** [comment]
[CodeFolio] 2/4 밋업 3명 참가합니다.

**Comment by kbu1564** [comment]
[SecurityBootManager] 2/4 밋업 2명 참가합니다.

**Comment by egaoneko** [comment]
[ward] 2/4 밋업 1명 참가합니다.

**Comment by MyeongKim** [comment]
@Kang-heesuk Lightening talk 신청합니다! Frontend Modular JavaScript에 대해 발표하고 싶습니다.

**Comment by kbu1564** [comment]
@Kang-heesuk Lightening talk 주제 : Boot Sequence and Hardware Abstraction in Operating System 으로 발표해보고 싶습니다.
시간은 30 ~ 40분 정도 생각하고 있습니다.

**Comment by Kang-heesuk** [comment]
@mingkim @kbu1564 오오 네네 좋습니다!!  :+1: 
두 분 talk 포함해서 일정 공지하도록 할께요~~

**Comment by Jungmo** [comment]
[SetupBox] 2월 4일 2명 참가합니다.

**Comment by Rumo-Arf** [comment]
[surro] 2명 참가 합니다.

**Comment by jcooky** [comment]
[Jandy] 1명 참가합니다

**Comment by MyeongKim** [comment]
발표자료입니다. https://slides.com/mingkim/frontend

**Comment by kbu1564** [comment]
[IWillFindYou_Boot_Sequence_and_Hardware_Abstraction_in_Operating_system.pptx](https://github.com/D2CAMPUS-FEST/2015/files/117028/IWillFindYou_Boot_Sequence_and_Hardware_Abstraction_in_Operating_system.pptx)

발표자료 링크 입니다.
