### ISSUE TITLE
[surro] 윈도우에서 git bash를 쓸 때 segmentation fault 에러

### ISSUE THREAD

**Issue by minarc** [D2CAMPUS-FEST/2015#29]

**Comment by Rumo-Arf** [comment]
시스템 환경 변수에서 문제가 생기는 것 같은데 한 번 환경 변수가 꼬이면 고치기 매우 귀찮은 것 같으니 그냥 업데이트를 안 하는 게 제일 좋겠습니다.

**Comment by Rumo-Arf** [comment]
https://twitter.com/demyte/status/692831900256186368

MS가 지금 고치는 중이랍니다... 아나.

**Comment by kbu1564** [comment]
win10  버그는 유명하죠
https://namu.wiki/w/Windows%2010/%EB%B2%84%EA%B7%B8

이런 위키글도 있을 정도 더라구요

**Comment by Rumo-Arf** [comment]
2.6.0 버전으로 git bash 구버전을 쓰면 local 이용에는 문제가 없지만 pull, push 등 네트워크 커넥션은 계속 미작동이네요.

**Comment by MyeongKim** [comment]
지금 git push 필요하시면 git bash 대신 https://www.sourcetreeapp.com/ 한번 사용해보세요.

**Comment by MyeongKim** [comment]
아, bash 문제가 아니라 git 문제였군요...

**Comment by Rumo-Arf** [comment]
@mingkim 대안 고맙습니다, 헌데 이게 시스템 환경 변수의 문제라 다른 git 클라이언트들도 동작이 영 시원찮더군요 Desktop 역시 마찬가지 였습니다. 말씀해 주신 SourceTreeApp 역시... 결국 git bash의 커맨드를 쓰는 지라.. 아래와 같군요.

![default](https://cloud.githubusercontent.com/assets/11865340/12722714/814eae8c-c949-11e5-88dc-0b0556635a8a.PNG)

현재로선 git bash 1.9.0를 설치해야만 다른 git 클라이언트들도 제대로 돌아간다고 하네요... 확인중에 있습니다.

**Comment by Rumo-Arf** [comment]
**크으, 결론은 지금 윈도우 10 x64 쓰시는 분들은 주의 바랍니다.**

**Comment by maxtortime** [comment]
저는 윈도우 10 쓰는데 git 사용 및 MinGW 쓸 때 한 번의 버그도 없었습니다..
제 생각엔 인사이더 프리뷰 버전이라 그러신 것 같습니다만..

**Comment by Rumo-Arf** [comment]
@maxyrtime 네, build 14251 입니다.
