### ISSUE TITLE
★ [공지] 세 번째 밋업 주제 제안 & 참가확인

### ISSUE THREAD

**Issue by Kang-heesuk** [D2CAMPUS-FEST/2015#30]
2월 18일(목) D2 StartupFactory에서 세 번째 밋업이 진행됩니다.
설 연휴로 인해 2주만에 다시 뵐 예정입니다.

그간 개발하던 내용 중 참가자들끼리 논의해보고 싶은 주제가 있다면 이슈로 등록해주세요~
발표(or 공유)하고 싶은 주제가 있다면 HOST로 Lightening talk을 진행해도 좋아요! :sparkles:

시간 : 오후 2시 - 7시

오후 2시 - 5시 : 자유롭게 프로젝트 개발 및 토론 (개발자 Café처럼)
오후 5시 - 7시 : Lightening Talk 참가자끼리 서로 주제에 대해 생각을 나누고 토론 

※ 밋업에 참여를 원하시는 분은 댓글과 주제 남겨주세요!

**Comment by MyeongKim** [comment]
[QuesCheetah] 2/18 밋업 1명 참가합니다.

**Comment by jafffy** [comment]
이날 Lightening Talk 진행하겠습니다. 

주제는 <나는 어떻게 시스템 프로그래밍에 입문하게 되었는가> 입니다.

**Comment by MyeongKim** [comment]
Lightening Talk 신청합니다.

**Comment by Kang-heesuk** [comment]
@jafffy @mingkim 네 확인했습니다 :)

Talk은 2개로 한정되어있는 것은 아니니 주제가 있으신 분은 더 올려주세요!

**Comment by egaoneko** [comment]
[ward] 2/18 밋업 2명 참가합니다.

**Comment by kbu1564** [comment]
[SecurityBootManager] 2/18 밋업 3명 참가합니다.!!

**Comment by jcooky** [comment]
[Jandy] 2/18 밋업 1명 참가합니다

**Comment by Jungmo** [comment]
[SetupBox] 2/18 밋업 3명 참가합니다.

**Comment by MyeongKim** [comment]
제 주제는 "2016 JavaScript Chart 라이브러리 비교" 입니다.

**Comment by egaoneko** [comment]
@mingkim 저희도 Chart 라이브러리를 사용해서 기대되는 주제이네요. :)

**Comment by maxtortime** [comment]
@mingkim 차트 라이브러리라면 [D3js](https://d3js.org/)나 [Processing](http://processingjs.org/) 인건가요 ㅎㅎ  비교라니 기대되는 주제네요.

**Comment by MyeongKim** [comment]
@egaoneko @maxtortime 앗. 재미없는 주제가 될 것 같아서 최종 결정이 늦어졌는데.. 관심 가져주셔서 감사합니다.

**Comment by haeri56** [comment]
[Performance-Navigator] 2/18 밋업 2명 참가합니다!

**Comment by Kang-heesuk** [comment]
@mingkim 오 주제 좋네요!! 이번 주도 기대하겠습니다 :D 우왕

**Comment by MyeongKim** [comment]
발표자료 링크입니다~ http://slides.com/mingkim/chart-library-comparison
