### ISSUE TITLE
[SetupBox] 어떻게 하면 디렉토리의 어떤 파일이 modify 되었는지 알 수 있을까요?

### ISSUE THREAD

**Issue by jafffy** [D2CAMPUS-FEST/2015#33]
구현하다가 아이디어를 얻고 싶어 issue 남깁니다.

저희 프로젝트의 경우, 여타 VCS가 그렇듯 어떠한 파일이 변화가 일어났다는 것을 감지할 필요가 있습니다.

이러한 기능을 어떻게 구현하면 좋을까요?

현재 제 아이디어는
- 뺑뺑이를 돌면서 diff를 뜬다. => Worst
- User level file system을 붙이고 write call 과 같이 파일에 변화를 일으키는 system call을 hooking 해서 변경의 척도로 삼는다. => Windows에서 User level file system을 사용하는 것이 어려운 면이 있음(그런데 git은 이런거 없이도 잘 하던데...)

이정도인데 혹시 좋은 아이디어 갖고 계신 분 계신가요?

**Comment by MyeongKim** [comment]
구글링해서 찾은 file change detection 알고리즘입니다. 
https://msdn.microsoft.com/en-us/library/bb902836(v=sql.110).aspx#Anchor_1

git 에서는 lstat를 사용해서 비교하는것 같습니다.
http://stackoverflow.com/questions/4075528/what-algorithm-git-uses-to-detect-the-changes-on-your-working-tree

**Comment by jafffy** [comment]
@mingkim 항상 감사합니다.
사실 lstat 뺑뺑이에 대해서는 고려는 하고 있었지만 O(N)인 작업이라 vcs의 scalability에 문제가 될 것 같아서 고민을 했었는데 git도 그런 방식을 사용한다니 안심이 좀 되네요. 적극적으로 그 방향으로 고려해보겠습니다. 감사합니다.
