### ISSUE TITLE
★ [공지] 마지막 밋업 발표 신청  & 참가확인

### ISSUE THREAD

**Issue by Kang-heesuk** [D2CAMPUS-FEST/2015#35]
벌써 마지막 밋업공지네요!

결승전 이전 마지막 밋업이니 Talk 하고 싶으신 주제가 있다면 마지막 밋업을 놓치지 마세요!
특별 게스트도 함께 할 예정입니다 :)

일시 : 2월 29일(월) 오후 2시 - 7시

오후 2시 - 5시 : 자유롭게 프로젝트 개발 및 토론 (개발자 Café처럼)
오후 5시 - 7시 : Lightening Talk 참가자끼리 서로 주제에 대해 생각을 나누고 토론 + 특별 게스트도 함께!

※ 밋업에 참여를 원하시는 분은 댓글과 발표 주제 남겨주세요!

**Comment by Yoseob** [comment]
Trevi 팀 전원 참석합니당.

**Comment by MyeongKim** [comment]
[QuesCheetah] 2/29 밋업 1명 참가합니다.

**Comment by disjukr** [comment]
yaksok.js 한 명 참석합니다.

**Comment by kbu1564** [comment]
[SecurityBootManager] 2/29 밋업 2명 참가합니다.

**Comment by MyeongKim** [comment]
Lightening Talk 신청합니당!

**Comment by egaoneko** [comment]
ward 팀 전원 참석합니다.

**Comment by Rumo-Arf** [comment]
Surro, 둘 참석.

**Comment by jcooky** [comment]
[Jandy] 2/29 밋업 1명 참가합니다.

그리고 Lightening Talk 신청합니다.

**Comment by MyeongKim** [comment]
Lightening Talk 주제는 [Play with CI Tools] 입니다.
발표 자료 링크는 http://slides.com/mingkim/ci-tools 입니다.

**Comment by haeri56** [comment]
[Performance Navigator] 2/29 밋업 2명 참석합니다!

**Comment by Kang-heesuk** [comment]
@jcooky 진성님- 발표해주신 발표자료 공유 가능할까요?? 가능하시다면 여기에 남겨주시거나 naver_d2@네이버닷컴으로 전달 부탁드려요 :) 감사합니다!!

**Comment by jcooky** [comment]
아 죄송합니다.

제목은 [오픈소스와 소프트웨어 성능 테스팅] 입니다.
발표자료 링크는 https://drive.google.com/file/d/0B9z5HWNVE0bgVDFBSE9ENWVvM0E/view?usp=sharing 입니다.
늦게 올리게 되어 죄송합니다.
