### ISSUE TITLE
Textbox의 특정 line no.로 자동 스크롤

### ISSUE THREAD

**Issue by minarc** [D2CAMPUS-FEST/2015#7]

**Comment by MyeongKim** [comment]
다른 방법은 아니지만, 
http://alexgorbatchev.com/SyntaxHighlighter/ 와 http://sunlightjs.com/ 홈페이지 예제의 경우 class 와 name 을 이용해 라인(넘버)별로 다른 속성을 가지고 있습니다.

github 에서도 data-line-number 라는 속성으로 숫자값을 각각 다르게 주고 있네요.

![2016-01-19 7 52 59](https://cloud.githubusercontent.com/assets/8112305/12416705/523581ec-bee6-11e5-9411-696a8faf0227.png)

**Comment by Rumo-Arf** [comment]
감사합니다, 덕분에 참고합니다.

SyntaxHighlighter를 사용 중이었는데 -,.-; 가만 생각 해 보면 단순한 문제였네요.

**Comment by kbu1564** [comment]
그냥 아이디어인데 라인별로 해시태그를 이용해서 해당 줄로 이동하는 것은 어떨까요?
깃허브에서 사용중인 방식처럼 제공해 주셔도 좋을것 같습니다.

**Comment by Rumo-Arf** [comment]
@kbu1564 예컨대 "#31"이라는 텍스트를 클릭하면 해당 줄로 이동하도록... 그렇게요?

**Comment by egaoneko** [comment]
설정해 놓으신 ID값을 url로 접근하면 안되는 건가요?

예를 들면,

`https://github.com/D2CAMPUS-FEST/2015/issues/7#issuecomment-173061652`

이렇게 url뒤에 #을 붙여서요.

**Comment by Rumo-Arf** [comment]
@egaoneko 음... 결국 그렇게 모든 라인에 id 값을 설정 해야 되는 걸까요. 이게 1천 라인 2천 라인이 될 수도 있는 문제라 뜸들여지네요.

**Comment by egaoneko** [comment]
@Rumo-Arf 어떤 곳에서 사용되는 부분인가요?

https://jsperf.com/id-vs-class-vs-tag-selectors/2
http://stackoverflow.com/questions/1230636/css-optimization-element-id-vs-class
이 사이트의 내용대로라면 id, atribute 나 class를 써야만 되는 상황이라면 id값도 괜찮지 않을까요?

**Comment by Rumo-Arf** [comment]
@egaoneko [syntaxhighlighter](http://alexgorbatchev.com/SyntaxHighlighter/)라는 라이브러리를 사용 중인데요. 여기서의 line number에 자동 스크롤 되게 하려고 합니다.

**Comment by egaoneko** [comment]
@Rumo-Arf 그렇시군요. @mingkim 님 말씀대로 github에서 id값을 설정해서 사용하는 것이면 괜찮지 않을까요?

`https://github.com/egaoneko/ward/blob/master/www/archive/views.py#L1189` 이런식으로 id값을 사용하고 있는거보면요. :)

**Comment by Rumo-Arf** [comment]
@egaoneko 그렇죠.... 결국 라이브러리를 직접 손 봐야하는 상황이 -,.-... MIT 라이센스라 다행인 것 같습니다. 감사합니다.

**Comment by kbu1564** [comment]
@Rumo-Arf 지금에서야 봤네요.
제가 말하려던것이 해시 태그를 이용한 "주소#L13" 방식이 맞습니다.

링크태그의 name 속성값으로 이동하는 방식이 해시태그 이므로 아마 수정에 문제가 없으실것 같아 한번 작성해 보았었습니다.

제 생각으로는 id 옵션을 너무 많이 사용하는것은 좋지 않을 것 같습니다.

id 옵션을 부여한 값이 많아 질 수록 브라우져의 javascript 엔진 dom 객체가 컨트롤하고 관리해야 할 객체의 아이디가 증가하게 되므로 **a 태그에 name 값 부여**를 통해 해시주소와 같이 페이지 리다이렉션 없이 단순히 해당 위치로 스크롤만 이동하도록 해도 좋을 것 같습니다.

**Comment by Rumo-Arf** [comment]
@kbu1564 역시, 예상했던 대로 성능의 문제가...... 좋은 답변 감사합니다.
