### ISSUE TITLE
[Teamkerbell] 개발 관련 Issue

### ISSUE THREAD

**Issue by seongahjo** [D2CAMPUS-FEST/2015#9]
현재 진행중인 프로젝트에서 타임라인이나 알림을 비동기식으로 확인할 수 있는 기능을 만들고 있습니다.
처음에는 이러한 기능을 Long polling을 이용하여 구현하려했으나
클라이언트에서 Request를 보내고 서버에서 Response를 받는 구조로는 
liveness를 구현하기에 한계가 있다고 판단하여 Websocket을 이용하여 개발중입니다.
현재 네이버에서 서비스하는 실시간 검색어 기능이 현재 저희가 구현하고자 하는 기능과 유사하다는 생각이 들어
네이버의 실시간 검색의 기능은 어떤식으로 데이터를 받아오는지 궁금하여 질문합니다. 
만일 해당 기능이 Comet으로 구현되있다면 Websocket으로 바꾸지 않은 이유가 있는지 궁금합니다.
만약 있다면 Websocket으로 인해 발생할 Issue들이 궁금합니다.
- 죄송합니다. 설명이 부족했네요 여기서 알림은 PC 웹환경에서의 알림을 뜻합니다.  PC버전의 페이스북에서
  친구요청이 오면 실시간으로 알림이 뜨는 기능이라고 생각하시면 이해하기 쉬우실 겁니다.

URL : https://github.com/seongahjo/Teamkerbell

**Comment by Rumo-Arf** [comment]
아마 '알림'을 확인 한 다는 것은 모바일에서의 알림을 말하는 것 인가요?
Teamkerbell ReadMe를 읽어보니 PC의 웹 브라우저에서 알림을 확인 한다는 말 같기도 하고......

**Comment by maxtortime** [comment]
저도 잘 몰라서 도움이 되는 답변을 드리기는 힘드네요... 하지만 클라이언트가 데이터를 받아오는 거면 그냥 ajax 이용하셔서 Long polling으로 충분하지 않을까 하는 생각이 들긴 합니다.

**Comment by Rumo-Arf** [comment]
WebSocket과 Ajax 속도를 비교한 블로그가 있었네요. 극도로 높은 성능이 필요한 경우는 아닌 것 같지만... 

[블로그](http://m.mkexdev.net/98)
[사진](http://cfile9.uf.tistory.com/original/18183F334CA42DDE2D6A02)

아래 링크에서는 또 WebSocket이 Notification에 알맞다고 하는 말도 있군요.

http://stackoverflow.com/questions/31035467/push-notification-is-websocket-mandatory

**Comment by maxtortime** [comment]
관련 자료 하나 올려봅니다.
http://techoctave.com/c7/posts/60-simple-long-polling-example-with-javascript-and-jquery/
